version: '3.9'
services:
  sb_app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3013 -b '0.0.0.0'"
    image: "example-third-party-app"
    volumes:
      - .:/Switchboard
    ports:
      - "3013:3013"
    extra_hosts:
      - "app.myclio.ca:${DOCKER_HOST_IP:-127.0.0.1}"
      - "account.myclio.ca:${DOCKER_HOST_IP:-127.0.0.1}"
